# Used https://raw.githubusercontent.com/Piturnah/gex/master/.github/workflows/cd.yml
name: CD

permissions:
  contents: write

on:
  release:
    types: [created]

jobs:
  bins:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Build and upload Rust binary to GitHub Releases
        uses: taiki-e/upload-rust-binary-action@v1.11.1
        with:
          bin: gex
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          CARGO_PROFILE_RELEASE_LTO: true
          CARGO_PROFILE_RELEASE_CODEGEN_UNITS: 1
